% -------------------------------------------------------------------
%  Generated by MATLAB on 14-Nov-2023 22:53:46
%  MATLAB version: 9.14.0.2206163 (R2023a)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

actual_price = 88.27;

data = saveVarsMat.data; % <1x1 table> unsupported class

endTime = saveVarsMat.endTime; % <1x1 duration> unsupported class

forecast_horizon = 1;

forecasted_price = 101.95464280817043;

mae = 13.684642808170437;

model = saveVarsMat.model; % <1x1 arima> unsupported class

mse = 187.26944878721088;

prices = saveVarsMat.prices; % <8761x1 double> too many elements

split_idx = 7009;

startTime = saveVarsMat.startTime; % <1x1 duration> unsupported class

test_prices = saveVarsMat.test_prices; % <1752x1 double> too many elements

test_timestamps = saveVarsMat.test_timestamps; % <1x1 datetime> unsupported class

timePeriods = saveVarsMat.timePeriods; % <8761x2 cell> too many elements

timestamps = saveVarsMat.timestamps; % <1x1 datetime> unsupported class

train_prices = saveVarsMat.train_prices; % <7009x1 double> too many elements

train_ratio = 0.8;

train_timestamps = saveVarsMat.train_timestamps; % <1x1 datetime> unsupported class

clear saveVarsMat;
